### ISSUE TITLE
Lat-lng (leaflet) vs lon-lat (GeoJSON)

### ISSUE THREAD

**Issue by orcaomar** [mkfreeman/norc-map#2]
Turns out [this is a design decision for each library](https://gis.stackexchange.com/questions/244651/leafletgeojson-why-are-lat-lng-coordinates-in-the-wrong-order), and there's a static function to deal with it, which I assume just reverses them but anyway here it is if you want to use it as opposed to what you're using:

L.GeoJson.coordsToLatLngs()

**Comment by mkfreeman** [comment]
Discussed in person, keeping as is.
