### ISSUE TITLE
deploy script and issues with data updates

### ISSUE THREAD

**Issue by orcaomar** [mkfreeman/norc-map#23]
First, very cool, the auto deploy all within github. Love it.

I updated the output_paths_with_data.geojson and pushed it. It seems this triggered the rebuild, but when I look at this file on the website:

http://mfviz.com/norc-map/output_paths_with_data.geojson

it appears to still be old. You can see this in a number of ways, but I was working on fixing 138 Bonis .. I figured out the error that led to the wrong shortest path, but the new distance should be 475, and yet it seems the old path is still available. 

I tried loading in different browsers thinking it was a cache thing, but that didn't seem to resolve it.

**Comment by orcaomar** [comment]
I thought it might be related to caching ie

https://stackoverflow.com/questions/24851824/how-long-does-it-take-for-github-page-to-show-changes-after-changing-index-html

but I don't think this is it.. I think I need to understand how the data gets pulled into the build process. Like do I need to put this on a realease branch or something like that?

**Comment by mkfreeman** [comment]
@orcaomar You need to run `yarn build` and then push to update the site. There isn't an action set up currently to do this automatically, though we could maybe configure that. 

It's kind of nice to be able to push to the main branch without affecting what they're looking at on the website though.

**Comment by orcaomar** [comment]
ah great, yes that makes sense. i ran the yarn build, and committed. thanks
