### ISSUE TITLE
Hide "geom" column in data table below the map

### ISSUE THREAD

**Issue by orcaomar** [mkfreeman/norc-map#34]
It should be so easy to just hide/remove a column when setting up the table, but I really didn't see an elegant way to do it and that's just my bad with data processing in JavaScript which I'm sure you'll know how to do right away. 

I didn't yarn build my previous change to load from the CSV yet because I wanted you to look at this issue, and see if there might be any others that cropped up in my change.

**Comment by mkfreeman** [comment]
Yea, this is surprisingly a bit of a pain. This [SO](https://stackoverflow.com/questions/34698905/how-can-i-clone-a-javascript-object-except-for-one-key) post is probably the most straightforward. I'm happy to implement this when passing the data to the Table [here](https://github.com/mkfreeman/norc-map/blob/748fd1acd01f5a120c4644fafd8154c0ee4ce076/src/App.svelte#L270).
