### ISSUE TITLE
Bench data as incorporated into the app is invalid

### ISSUE THREAD

**Issue by orcaomar** [mkfreeman/norc-map#35]
It turns out that shelters have a correspondence with TTC stops, but furniture data has no ID that links it with TTC stops. That is, the City doesn't appear, at least on my analysis of their furniture data, to make any attempt to link a given bench to a TTC stop.

I will need to do this and regenerate the bench and amenity data. This will change a few things.

**Comment by orcaomar** [comment]
ok @mkfreeman you're not going to love this, but I went back through the bench data which i was skeptical about and realized that there is no join field for that data, rather I had to:
- take all stops, and compute a 10 meter buffer around them (10 m because the stop coordinates and the bench coordinates have a bit of give, aren't totally accurate from what I can tell, esp. benches)
- count how many benches from the City bench data fall within those buffers
- if a stop has > 0 benches within it, then I add a "Bench Nearby" amenity. So now the amenity property is a list.. you'll see it when you load up my changes

blah plot thickens for the visualization

**Comment by mkfreeman** [comment]
@orcaomar hmmmm.... tricky indeed! I'm not sure we want to track a list of _amenities_. For example, probably not super valuable to know that there is a bench nearby when there is a bench underneath the shelter. Feels like it would require a lot of reworking for the interaction to incorporate this information, of which there are only a handful of instances (35 total). 

I can think of a few options, but you'll likely have a better idea given that you're closer to the data:
- Only add "bench nearby" when there is no other amenity (n = 7)
- Only add "bench nearby" when there is no bench (e.g., there's nothing - 7 - or there's a shelter with no bench, n = 2). 
- Remove the bench nearby information entirely (feels like a loss of some good work though!)
- Combine the list into a string and display all possibly combination (e.g. "Shelter with bench underneath with bench nearby" (this is my least favorite) 

My broader concern is that we're adding another layer of uncertainty to the data quality, of which there is already quite a bit of concern. Regardless, we'll want to document very clearly what all of these columns mean, and how they're calculated.

**Comment by orcaomar** [comment]
Ok, perhaps we leave the data in the spreadsheet (ie leave the number of benches nearby), BUT do as you said for point 1 and 2 -- bench nearby when no other amenity OR a shelter without a bench. 

I can update the amenity column with this decision. Hopefully will do today or tomorrow.

**Comment by mkfreeman** [comment]
Sounds good, thanks much! Lemme know if you need anything on my end.

**Comment by orcaomar** [comment]
Ok this is done. I manually copied the new CSV data into the Google Sheet Here: https://docs.google.com/spreadsheets/d/1NbU26zUWP9rhzm2W5weNxPFgq-yLUGxmDKtGoKA29i4/edit#gid=235556273

Same sheet as before. I haven't yard builded this as @mkfreeman needs to (I think?) make some changes for aesthetics prior to making public for them? If not, then just check it out and yarn build it if all good.

**Comment by mkfreeman** [comment]
@orcaomar nice! Just updated the code ([fe865c5](https://github.com/mkfreeman/norc-map/commit/fe865c5a5e49c11d267d3e9dcd5798333711de70)), will do a few more fixes then build.
